# Generated by Django 4.2.2 on 2023-06-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships2023', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='usn',
        ),
    ]
