# Generated by Django 4.2.2 on 2023-07-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships2023', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='contact',
            new_name='internship',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='username',
            new_name='phoneno',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
    ]
