# Generated by Django 4.2.2 on 2023-07-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships2023', '0004_delete_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='internship',
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phoneno',
            field=models.CharField(max_length=20),
        ),
    ]
