# Generated by Django 4.2.2 on 2023-07-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships2023', '0005_remove_registration_internship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='internshipprogram',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
